name: Go Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...
